// <auto-generated />
using System;
using Calculator.Shared.EntityFramework.Configs;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Calculator.Shared.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Calculator.Shared.EntityFramework.Entities.TaxEntities.TaxRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("MonetaryUnit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TaxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("TaxRule");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Gothenburg",
                            Country = "Sweden",
                            CreatedAt = new DateTime(2024, 1, 26, 21, 46, 9, 92, DateTimeKind.Local).AddTicks(485),
                            EndTime = new DateTime(2013, 1, 10, 6, 29, 0, 0, DateTimeKind.Unspecified),
                            MonetaryUnit = "SEK",
                            StartTime = new DateTime(2013, 1, 10, 6, 0, 0, 0, DateTimeKind.Unspecified),
                            TaxAmount = 8m,
                            UpdatedAt = new DateTime(2024, 1, 26, 21, 46, 9, 92, DateTimeKind.Local).AddTicks(496)
                        },
                        new
                        {
                            Id = 2,
                            City = "Gothenburg",
                            Country = "Sweden",
                            CreatedAt = new DateTime(2024, 1, 26, 21, 46, 9, 92, DateTimeKind.Local).AddTicks(557),
                            EndTime = new DateTime(2013, 1, 10, 6, 59, 0, 0, DateTimeKind.Unspecified),
                            MonetaryUnit = "SEK",
                            StartTime = new DateTime(2013, 1, 10, 6, 30, 0, 0, DateTimeKind.Unspecified),
                            TaxAmount = 13m,
                            UpdatedAt = new DateTime(2024, 1, 26, 21, 46, 9, 92, DateTimeKind.Local).AddTicks(558)
                        },
                        new
                        {
                            Id = 3,
                            City = "Gothenburg",
                            Country = "Sweden",
                            CreatedAt = new DateTime(2024, 1, 26, 21, 46, 9, 92, DateTimeKind.Local).AddTicks(561),
                            EndTime = new DateTime(2013, 1, 10, 7, 59, 0, 0, DateTimeKind.Unspecified),
                            MonetaryUnit = "SEK",
                            StartTime = new DateTime(2013, 1, 10, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            TaxAmount = 18m,
                            UpdatedAt = new DateTime(2024, 1, 26, 21, 46, 9, 92, DateTimeKind.Local).AddTicks(562)
                        },
                        new
                        {
                            Id = 4,
                            City = "Gothenburg",
                            Country = "Sweden",
                            CreatedAt = new DateTime(2024, 1, 26, 21, 46, 9, 92, DateTimeKind.Local).AddTicks(565),
                            EndTime = new DateTime(2013, 1, 10, 8, 29, 0, 0, DateTimeKind.Unspecified),
                            MonetaryUnit = "SEK",
                            StartTime = new DateTime(2013, 1, 10, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            TaxAmount = 13m,
                            UpdatedAt = new DateTime(2024, 1, 26, 21, 46, 9, 92, DateTimeKind.Local).AddTicks(566)
                        },
                        new
                        {
                            Id = 5,
                            City = "Gothenburg",
                            Country = "Sweden",
                            CreatedAt = new DateTime(2024, 1, 26, 21, 46, 9, 92, DateTimeKind.Local).AddTicks(569),
                            EndTime = new DateTime(2013, 1, 10, 14, 59, 0, 0, DateTimeKind.Unspecified),
                            MonetaryUnit = "SEK",
                            StartTime = new DateTime(2013, 1, 10, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            TaxAmount = 8m,
                            UpdatedAt = new DateTime(2024, 1, 26, 21, 46, 9, 92, DateTimeKind.Local).AddTicks(570)
                        },
                        new
                        {
                            Id = 6,
                            City = "Gothenburg",
                            Country = "Sweden",
                            CreatedAt = new DateTime(2024, 1, 26, 21, 46, 9, 92, DateTimeKind.Local).AddTicks(575),
                            EndTime = new DateTime(2013, 1, 10, 15, 29, 0, 0, DateTimeKind.Unspecified),
                            MonetaryUnit = "SEK",
                            StartTime = new DateTime(2013, 1, 10, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            TaxAmount = 13m,
                            UpdatedAt = new DateTime(2024, 1, 26, 21, 46, 9, 92, DateTimeKind.Local).AddTicks(576)
                        },
                        new
                        {
                            Id = 7,
                            City = "Gothenburg",
                            Country = "Sweden",
                            CreatedAt = new DateTime(2024, 1, 26, 21, 46, 9, 92, DateTimeKind.Local).AddTicks(579),
                            EndTime = new DateTime(2013, 1, 10, 16, 59, 0, 0, DateTimeKind.Unspecified),
                            MonetaryUnit = "SEK",
                            StartTime = new DateTime(2013, 1, 10, 15, 30, 0, 0, DateTimeKind.Unspecified),
                            TaxAmount = 18m,
                            UpdatedAt = new DateTime(2024, 1, 26, 21, 46, 9, 92, DateTimeKind.Local).AddTicks(580)
                        },
                        new
                        {
                            Id = 8,
                            City = "Gothenburg",
                            Country = "Sweden",
                            CreatedAt = new DateTime(2024, 1, 26, 21, 46, 9, 92, DateTimeKind.Local).AddTicks(582),
                            EndTime = new DateTime(2013, 1, 10, 17, 59, 0, 0, DateTimeKind.Unspecified),
                            MonetaryUnit = "SEK",
                            StartTime = new DateTime(2013, 1, 10, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            TaxAmount = 13m,
                            UpdatedAt = new DateTime(2024, 1, 26, 21, 46, 9, 92, DateTimeKind.Local).AddTicks(583)
                        },
                        new
                        {
                            Id = 9,
                            City = "Gothenburg",
                            Country = "Sweden",
                            CreatedAt = new DateTime(2024, 1, 26, 21, 46, 9, 92, DateTimeKind.Local).AddTicks(586),
                            EndTime = new DateTime(2013, 1, 10, 18, 29, 0, 0, DateTimeKind.Unspecified),
                            MonetaryUnit = "SEK",
                            StartTime = new DateTime(2013, 1, 10, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            TaxAmount = 8m,
                            UpdatedAt = new DateTime(2024, 1, 26, 21, 46, 9, 92, DateTimeKind.Local).AddTicks(587)
                        },
                        new
                        {
                            Id = 10,
                            City = "Gothenburg",
                            Country = "Sweden",
                            CreatedAt = new DateTime(2024, 1, 26, 21, 46, 9, 92, DateTimeKind.Local).AddTicks(592),
                            EndTime = new DateTime(2013, 1, 10, 5, 59, 0, 0, DateTimeKind.Unspecified),
                            MonetaryUnit = "SEK",
                            StartTime = new DateTime(2013, 1, 10, 18, 30, 0, 0, DateTimeKind.Unspecified),
                            TaxAmount = 0m,
                            UpdatedAt = new DateTime(2024, 1, 26, 21, 46, 9, 92, DateTimeKind.Local).AddTicks(593)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
